### ISSUE TITLE
I can't see what I'm clicking

### ISSUE THREAD

**Issue by SWest2019** [tobloef/roll20-fancy-dice#2]
I can not see what I am clicking. It shows a white screen when I pull up the original screen, I figured out where the mouse switched to the hand when over a link, clicked it, and then selected dice and then idk what is on the next screen but I can not figure out a way to use my dice...help???

**Comment by tobloef** [comment]
Hey there. I assume you're talking about the popup that should open when you click the extension's blue dice icon, right? It should look something like this:

![image](https://user-images.githubusercontent.com/12204005/79041854-63366500-7bf3-11ea-8a8c-278fc1fff74f.png)

But it's completely blank for you, is that correct?

**Comment by SWest2019** [comment]
yeah...I figured it out, I had to restart my roll20

**Comment by tobloef** [comment]
Great to hear you got it working 👍
