### ISSUE TITLE
Roll20 Update

### ISSUE THREAD

**Issue by over2take** [tobloef/roll20-fancy-dice#7]
Was working on some custom dice and in the middle of testing Roll 20 updated braking the extension. 

FANCYDICE: Hook "Expose D20 globally" failed to inject, no matching pattern in file https://app.roll20.net/assets/app.js?1608654391.

stack trace: 
content-script.js:1194 (warn)
content-script.js:587 (injectHooks)
content-script.js:533 (hookAndInsertScripts)

**Comment by tobloef** [comment]
Thanks for letting me know. I have fixed the issues, as well as made the hooks more robust for future Roll20 updates. The update has been submitted and it should be live in a few hours.

Also, very much looking forward to seeing any custom dice you make. Cheers!
