### ISSUE TITLE
Dice Won't Roll

### ISSUE THREAD

**Issue by geekdadenergy** [tobloef/roll20-fancy-dice#9]
Greetings,

I tried to use your extension but the dice are not rolling. I got this error message; 
<$ if(this.type == 'gmrollresult') { $>
<$ } else if(this.playerid == window.currentPlayer.id) { $>
<$ } else { $>
<$ } $><$ if(this.showname) { $>
<$ if(this.avatar) { $><$ } $><$!this.who$>:<$ } $><$ if(this.type == 'gmrollresult') { $>(To GM)<$ } $>rolling <$=this.sanitizedOrigRoll$>
<$= d20ext.utils.strip_tags(this.htmlcontent.formula, d20ext.utils.htmlAllowed, true) $>
=<$! this.htmlcontent.total $><$ if(this.failedSignature) { $>
Something seems to be wrong with the above roll -- it failed verification.
<$ } $>

Not sure what to do, I do have the VTTES installed as well. Any assistance is appreciated

**Comment by tobloef** [comment]
Unfortunately there's a conflict between VTTES and this extension, so you won't be able to use both at the same time. Sorry about that.

**Comment by Markus1204** [comment]
Even without VTTES installed no dices will roll! This extension is basically useless! Without your extension, 3D Dice will roll without any problem...

**Comment by tobloef** [comment]
As described in the README, this happens every once in a while when Roll20 updates their app. I have fixed the issue and sent the update to Google. It may be a few hours before it's available.
